multiThread:
  batchSize: 50000
  elasticSearchBulkSize: 50000
  readerThreadsCount: 10

elasticsearch:
  elasticsearch.host: ${ELASTIC_SEARCH_HOST:-localhost}
  elasticsearch.port: ${ELASTIC_SEARCH_PORT:-9200}

  elasticsearch.additional.nodes:
    - localhost:9200
    - localhost:9200

  elasticsearch.cluster: ${ELASTIC_SEARCH_CLUSTER:-elasticsearch}
  elasticsearch.alias: ${ELASTIC_SEARCH_ALIAS:-facilities}
  elasticsearch.index.prefix: facilities_cws
  elasticsearch.doctype: ${ELASTIC_SEARCH_DOCTYPE:-facility}
  #
  elasticsearch.xpack.user: ${ELASTIC_SEARCH_XPACK_USER:-elastic}
  elasticsearch.xpack.password: ${ELASTIC_SEARCH_XPACK_PASSWORD:-changeme}

cmsDataSourceFactory:
  properties:
      hibernate.dialect: gov.ca.cwds.jobs.cals.facility.cws.CustomDb2Dialect
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.connection.driver_class: com.ibm.db2.jcc.DB2Driver
      hibernate.show_sql: false
      hibernate.format_sql: false
      hibernate.use_sql_comments: false
      hibernate.connection.username: ${DB_CMS_USER:-x}
      hibernate.connection.password: ${DB_CMS_PASSWORD:-x}
      hibernate.connection.url: ${DB_CMS_JDBC_URL:-jdbc:db2://10.211.5.36:4016/DBN1SOC:retrieveMessagesFromServerOnGetMessage=true;emulateParameterMetaDataForZCalls=1;allowNextOnExhaustedResultSet=1;resultSetHoldability=2;queryTimeoutInterruptProcessingMode=2;queryCloseImplicit=1; queryDataSize=266143;}
      hibernate.default_schema: ${DB_CMS_SCHEMA:-CWSRS1}
      hibernate.connection.connectionTimeout: 1000000
      hibernate.connection.loginTimeout: 1000000
      hibernate.connection.keepAliveTimeOut: 8
      hibernate.jdbc.time_zone: America/Los_Angeles
      hibernate.jdbc.use_scrollable_resultset: true
      hibernate.connection.provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
      hibernate.hikari.minimumIdle: 4
      hibernate.hikari.maximumPoolSize: 10
      hibernate.hikari.maxLifetime: 900000
      hibernate.hikari.idleTimeout: 90000
      hibernate.hikari.connectionTimeout: 45000
      hibernate.hikari.registerMbeans: true

calsnsDataSourceFactory:
  properties:
      hibernate.dialect: gov.ca.cwds.cals.persistence.hibernate.dialect.JsonbSupportPostgreSQL9Dialect
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.connection.driver_class: org.postgresql.Driver
      hibernate.show_sql: false
      hibernate.format_sql: false
      hibernate.use_sql_comments: false
      hibernate.connection.username: ${DB_NS_USER:-x}
      hibernate.connection.password: ${DB_NS_PASSWORD:-x}
      hibernate.connection.url: ${DB_NS_JDBC_URL:-jdbc:postgresql://postgresql.integration.cwds.io:5432/integration}
      hibernate.default_schema: ${DB_NS_DEFAULT_SCHEMA:-calsns}
      hibernate.connection.connectionTimeout: 1000000
      hibernate.connection.loginTimeout: 1000000
      hibernate.connection.keepAliveTimeOut: 8
      hibernate.jdbc.time_zone: America/Los_Angeles
      hibernate.jdbc.use_scrollable_resultset: true
      hibernate.id.new_generator_mappings: false
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      hibernate.cache.use_query_cache: true
      hibernate.connection.autocommit: false
      hibernate.connection.provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
      hibernate.hikari.minimumIdle: 4
      hibernate.hikari.maximumPoolSize: 10
      hibernate.hikari.maxLifetime: 900000
      hibernate.hikari.idleTimeout: 90000
      hibernate.hikari.connectionTimeout: 45000
      hibernate.hikari.registerMbeans: true
