batchSize: 500
elasticSearchBulkSize: 500
readerThreadsCount: 1

elasticsearch.host: ${ELASTIC_SEARCH_HOST:-localhost}
elasticsearch.port: ${ELASTIC_SEARCH_PORT:-9200}

elasticsearch.additional.nodes:
  - localhost:9200
  - localhost:9200

elasticsearch.cluster: ${ELASTIC_SEARCH_CLUSTER:-elasticsearch}
elasticsearch.alias: ${ELASTIC_SEARCH_ALIAS:-facilities}
elasticsearch.index.prefix: facilities_cws
elasticsearch.doctype: ${ELASTIC_SEARCH_DOCTYPE:-facility}
#
elasticsearch.xpack.user: ${ELASTIC_SEARCH_XPACK_USER:-elastic}
elasticsearch.xpack.password: ${ELASTIC_SEARCH_XPACK_PASSWORD:-changeme}

cmsDataSourceFactory:
  properties:
      hibernate.dialect: org.hibernate.dialect.DB2Dialect
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.connection.driver_class: com.ibm.db2.jcc.DB2Driver
      hibernate.show_sql: false
      hibernate.format_sql: true
      hibernate.use_sql_comments: false
      hibernate.connection.username: ${DB_CMS_USER:-db2inst1}
      hibernate.connection.password: ${DB_CMS_PASSWORD:-db2inst1-pwd}
      hibernate.connection.url: ${DB_CMS_JDBC_URL:-jdbc:db2://localhost:50000/DB0TDEV}
      hibernate.default_schema: ${DB_CMS_SCHEMA:-CWSCMSRS}
      hibernate.connection.connectionTimeout: 1000000
      hibernate.connection.loginTimeout: 1000000
      hibernate.connection.keepAliveTimeOut: 8
      hibernate.jdbc.time_zone: America/Los_Angeles
      hibernate.jdbc.use_scrollable_resultset: true
      hibernate.connection.provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
      hibernate.hikari.minimumIdle: 4
      hibernate.hikari.maximumPoolSize: 10
      hibernate.hikari.maxLifetime: 900000
      hibernate.hikari.idleTimeout: 90000
      hibernate.hikari.connectionTimeout: 45000
      hibernate.hikari.registerMbeans: true

calsnsDataSourceFactory:
  properties:
      hibernate.dialect: gov.ca.cwds.cals.persistence.hibernate.dialect.JsonbSupportPostgreSQL9Dialect
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.connection.driver_class: org.postgresql.Driver
      hibernate.show_sql: false
      hibernate.format_sql: true
      hibernate.use_sql_comments: false
      hibernate.connection.username: ${DB_NS_USER:-postgres_data}
      hibernate.connection.password: ${DB_NS_PASSWORD:-postgres_data}
      hibernate.connection.url: ${DB_NS_JDBC_URL:-jdbc:postgresql://localhost:5432/postgres_data}
      hibernate.default_schema: ${DB_NS_DEFAULT_SCHEMA:-calsns}
      hibernate.connection.connectionTimeout: 1000000
      hibernate.connection.loginTimeout: 1000000
      hibernate.connection.keepAliveTimeOut: 8
      hibernate.jdbc.time_zone: America/Los_Angeles
      hibernate.jdbc.use_scrollable_resultset: true
      hibernate.id.new_generator_mappings: false
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      hibernate.cache.use_query_cache: true
      hibernate.connection.autocommit: false
      hibernate.connection.provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
      hibernate.hikari.minimumIdle: 4
      hibernate.hikari.maximumPoolSize: 10
      hibernate.hikari.maxLifetime: 900000
      hibernate.hikari.idleTimeout: 90000
      hibernate.hikari.connectionTimeout: 45000
      hibernate.hikari.registerMbeans: true
