elasticSearchBulkSize: 500

perryApiUrl: ${PERRY_URL:-http://localhost:18080/perry/idm}
perryApiUser: ${PERRY_USER:-user}
perryApiPassword: ${PERRY_PASS:-pass}
jerseyClientConnectTimeout: ${CONNECT_TIMEOUT:-20000}
jerseyClientReadTimeout: ${READ_TIMEOUT:-60000}

batchSize: ${PERRY_REQUEST_BATCH_SIZE:-100}
performanceTestMode: ${PERF_TEST_MODE_ON:-false}

awsRegion: ${AWS_REGION:-region}
awsAccessId: ${AWS_ACCESS_ID:-id}
awsAccessKey: ${AWS_ACCESS_KEY:-key}
awsBucketName: ${AWS_BUCKET_NAME:-cap-users-reports}

elasticsearch:
  elasticsearch.additional.nodes:
    - localhost:9300
    - localhost:9300

  elasticsearch.cluster: ${ELASTIC_SEARCH_CLUSTER:-elasticsearch_DimaS}
  elasticsearch.alias: ${ELASTIC_SEARCH_ALIAS:-users}
  elasticsearch.index.prefix: users
  elasticsearch.doctype: ${ELASTIC_SEARCH_DOCTYPE:-user}
  elasticsearch.host: ${ELASTIC_SEARCH_HOST:-localhost}
  elasticsearch.port: ${ELASTIC_SEARCH_PORT:-9300}
  #
  elasticsearch.xpack.user: ${ELASTIC_SEARCH_XPACK_USER:-elastic}
  elasticsearch.xpack.password: ${ELASTIC_SEARCH_XPACK_PASSWORD:-changeme}

cmsDataSourceFactory:
  properties:
    hibernate.dialect: org.hibernate.dialect.DB2Dialect
    hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate.connection.driver_class: com.ibm.db2.jcc.DB2Driver
    hibernate.show_sql: false
    hibernate.format_sql: false
    hibernate.use_sql_comments: false
    hibernate.connection.username: ${DB_CMS_USER:-db2inst1}
    hibernate.connection.password: ${DB_CMS_PASSWORD:-db2inst1}
    hibernate.connection.url: ${DB_CMS_JDBC_URL:-jdbc:db2://localhost:50000/DB0TDEV:retrieveMessagesFromServerOnGetMessage=true;emulateParameterMetaDataForZCalls=1;allowNextOnExhaustedResultSet=1;resultSetHoldability=2;queryTimeoutInterruptProcessingMode=2;queryCloseImplicit=1; queryDataSize=266143;}
    hibernate.default_schema: ${DB_CMS_SCHEMA:-CWSINT}
    hibernate.connection.connectionTimeout: 1000000
    hibernate.connection.loginTimeout: 1000000
    hibernate.connection.keepAliveTimeOut: 8
    hibernate.jdbc.time_zone: America/Los_Angeles
    hibernate.jdbc.use_scrollable_resultset: true
    hibernate.connection.provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
    hibernate.hikari.minimumIdle: 4
    hibernate.hikari.maximumPoolSize: 10
    hibernate.hikari.maxLifetime: 900000
    hibernate.hikari.idleTimeout: 90000
    hibernate.hikari.connectionTimeout: 45000
    hibernate.hikari.registerMbeans: true
